Models/ErrorViewModel.cs
using System;

namespace NBA_WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Igrac.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace NBA_WebApp.Models
{
    public class Igrac
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public string Pozicija { get; set; }
        public string Nadimak { get; set; }
        public int Broj_dresa { get; set; }

        public Igrac()
        {
            
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using NBA_WebApp.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace NBA_WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/IgracsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using NBA_WebApp.Data;
using NBA_WebApp.Models;

namespace NBA_WebApp.Controllers
{
    public class IgracsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public IgracsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Igracs
        public async Task<IActionResult> Index()
        {
            return View(await _context.Igrac.ToListAsync());
        }

        // GET: Igracs/ShowSearchForm
        public async Task<IActionResult> ShowSearchForm()
        {
            return View();
        }

        // PoST: Igracs/ShowSearchResults
        public async Task<IActionResult> ShowSearchResults(String PretraziIgraca)
        {
            return View("Index",await _context.Igrac.Where( j => j.Prezime.Contains(PretraziIgraca)).ToListAsync());
        }

        // GET: Igracs/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var igrac = await _context.Igrac
                .FirstOrDefaultAsync(m => m.Id == id);
            if (igrac == null)
            {
                return NotFound();
            }

            return View(igrac);
        }

        // GET: Igracs/Create
        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Igracs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Create([Bind("Id,Ime,Prezime,Pozicija,Nadimak,Broj_dresa")] Igrac igrac)
        {
            if (ModelState.IsValid)
            {
                _context.Add(igrac);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(igrac);
        }

        // GET: Igracs/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var igrac = await _context.Igrac.FindAsync(id);
            if (igrac == null)
            {
                return NotFound();
            }
            return View(igrac);
        }

        // POST: Igracs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Ime,Prezime,Pozicija,Nadimak,Broj_dresa")] Igrac igrac)
        {
            if (id != igrac.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(igrac);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!IgracExists(igrac.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(igrac);
        }

        // GET: Igracs/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var igrac = await _context.Igrac
                .FirstOrDefaultAsync(m => m.Id == id);
            if (igrac == null)
            {
                return NotFound();
            }

            return View(igrac);
        }

        // POST: Igracs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var igrac = await _context.Igrac.FindAsync(id);
            _context.Igrac.Remove(igrac);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool IgracExists(int id)
        {
            return _context.Igrac.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">NBA App</h1>
    <p>Web aplikacija za pregled NBA igrača.</p>
</div>

Views/Igracs/Create.cshtml
@model NBA_WebApp.Models.Igrac

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Igrac</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezime" class="control-label"></label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pozicija" class="control-label"></label>
                <input asp-for="Pozicija" class="form-control" />
                <span asp-validation-for="Pozicija" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nadimak" class="control-label"></label>
                <input asp-for="Nadimak" class="form-control" />
                <span asp-validation-for="Nadimak" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Broj_dresa" class="control-label"></label>
                <input asp-for="Broj_dresa" class="form-control" />
                <span asp-validation-for="Broj_dresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Igracs/Delete.cshtml
@model NBA_WebApp.Models.Igrac

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Igrac</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pozicija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pozicija)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nadimak)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nadimak)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Broj_dresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Broj_dresa)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Igracs/Details.cshtml
@model NBA_WebApp.Models.Igrac

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Igrac</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Ime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Ime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Prezime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Prezime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pozicija)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pozicija)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nadimak)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nadimak)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Broj_dresa)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Broj_dresa)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Igracs/Edit.cshtml
@model NBA_WebApp.Models.Igrac

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Igrac</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Ime" class="control-label"></label>
                <input asp-for="Ime" class="form-control" />
                <span asp-validation-for="Ime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prezime" class="control-label"></label>
                <input asp-for="Prezime" class="form-control" />
                <span asp-validation-for="Prezime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Pozicija" class="control-label"></label>
                <input asp-for="Pozicija" class="form-control" />
                <span asp-validation-for="Pozicija" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nadimak" class="control-label"></label>
                <input asp-for="Nadimak" class="form-control" />
                <span asp-validation-for="Nadimak" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Broj_dresa" class="control-label"></label>
                <input asp-for="Broj_dresa" class="form-control" />
                <span asp-validation-for="Broj_dresa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Igracs/Index.cshtml
@model IEnumerable<NBA_WebApp.Models.Igrac>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Ime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prezime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pozicija)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nadimak)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Broj_dresa)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Prezime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pozicija)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nadimak)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Broj_dresa)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Igracs/ShowSearchForm.cshtml
<h4>Pretrazi igraca</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="ShowSearchResults">
            
            
            <div class="form-group">
                <label for="PretraziIgraca" class="control-label"></label>
                <input name="PretraziIgraca" class="form-control" />
                
            </div>
            <div class="form-group">
                <input type="submit" value="Pretrazi" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NBA_WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NBA_WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Igracs" asp-action="Index">Igraci</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Igracs" asp-action="ShowSearchForm">Pretrazi</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - NBA_WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>